### ISSUE TITLE
spotted mistake troubleshotting mysql 8 error 1045

### ISSUE THREAD

**Issue by Zuwhity** [rizerkrof/cheatsheets#3]
The last command line you had isn't working any more on today's mysql version you should the following sentences:

``` 
mysql> FLUSH PRIVILEGES;
mysql> ALTER USER 'root'@'localhost' IDENTIFIED BY 'mysqlPassword34*';

```
Have fun editing

**Comment by rizerkrof** [comment]
Thank you for the issue! This has been solved.
